repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML==6.0.12]
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
      - id: black
        language_version: python3
        args: ['--config=pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        exclude: /tests/